import json
from pathlib import Path

NB_PATH = Path(r"c:\PROJETOS\PYTHON\APPS\estudo-twins-digital\tests\debug\modelo_perceptron.ipynb")

SMARTMLP_CODE = [
    "class SmartMLP:\n",
    "    \"\"\"\n",
    "    MLP com opção de ignorar parcial ou totalmente a camada oculta H2.\n",
    "    Quando use_h2=False, a saída conecta diretamente H1 -> Saída por pesos de bypass.\n",
    "    Quando use_h2=True, é possível ativar um subconjunto dos neurônios de H2 via máscara (h2_mask).\n",
    "    Durante o treinamento (try_both=True), testamos AUTOMATICAMENTE:\n",
    "      - bypass (0 neurônios H2)\n",
    "      - TODAS as combinações de 1..h2_size neurônios ativos em H2,\n",
    "    mantendo a configuração (máscara) que produzir o menor erro total.\n",
    "    \"\"\"\n",
    "    def __init__(self, initial_weights, input_size=3, h1_size=5, h2_size=4, output_size=1, use_h2=True):\n",
    "        # Pesos/vieses das camadas tradicionais (fornecidos externamente)\n",
    "        self.weights_h1 = initial_weights[\"weights_h1\"]\n",
    "        self.bias_h1 = initial_weights[\"bias_h1\"]\n",
    "        self.weights_h2 = initial_weights[\"weights_h2\"]\n",
    "        self.bias_h2 = initial_weights[\"bias_h2\"]\n",
    "        self.weights_out = initial_weights[\"weights_out\"]\n",
    "        self.bias_out = initial_weights[\"bias_out\"]\n",
    "\n",
    "        # Pesos/vieses para o caminho de bypass (H1 -> Saída). Inicializamos com zeros para\n",
    "        # garantir determinismo. Eles serão ajustados se use_h2=False vencer no treinamento.\n",
    "        import numpy as _np\n",
    "        self.weights_bypass_out = _np.zeros((h1_size, output_size))\n",
    "        self.bias_bypass_out = _np.zeros(output_size)\n",
    "\n",
    "        # Máscara de H2 (1.0 = ativo, 0.0 = inativo). Por padrão, todos ativos.\n",
    "        self.h2_mask = _np.ones(h2_size)\n",
    "\n",
    "        self.use_h2 = bool(use_h2)\n",
    "\n",
    "    def _sigmoid(self, x):\n",
    "        return 1 / (1 + np.exp(-x))\n",
    "\n",
    "    def _sigmoid_derivative(self, x):\n",
    "        return x * (1 - x)\n",
    "\n",
    "    def predict(self, inputs, use_h2=None):\n",
    "        \"\"\"\n",
    "        Forward pass que respeita a flag de uso da H2 e uma possível máscara de neurônios.\n",
    "        - Se use_h2=True: Entrada -> H1(sigmoid) -> H2(sigmoid & máscara) -> Out(sigmoid)\n",
    "        - Se use_h2=False: Entrada -> H1(sigmoid) -> Out_bypass(sigmoid)\n",
    "        \"\"\"\n",
    "        if use_h2 is None:\n",
    "            use_h2 = self.use_h2\n",
    "\n",
    "        # Camada H1\n",
    "        self.h1_output = self._sigmoid(np.dot(inputs, self.weights_h1) + self.bias_h1)\n",
    "\n",
    "        if use_h2:\n",
    "            # Camada H2\n",
    "            self.h2_output = self._sigmoid(np.dot(self.h1_output, self.weights_h2) + self.bias_h2)\n",
    "            # Aplicar máscara de H2 (neurônios inativos não contribuem)\n",
    "            self.h2_used = self.h2_output * self.h2_mask\n",
    "            # Saída final via H2 mascarada\n",
    "            final_output = self._sigmoid(np.dot(self.h2_used, self.weights_out) + self.bias_out)\n",
    "        else:\n",
    "            # Ignoramos H2 e usamos o caminho de bypass H1 -> Saída\n",
    "            final_output = self._sigmoid(np.dot(self.h1_output, self.weights_bypass_out) + self.bias_bypass_out)\n",
    "\n",
    "        return final_output\n",
    "\n",
    "    def _snapshot(self):\n",
    "        \"\"\"Cria um snapshot dos pesos atuais para comparar cenários.\"\"\"\n",
    "        return {\n",
    "            'weights_h1': self.weights_h1.copy(),\n",
    "            'bias_h1': self.bias_h1.copy(),\n",
    "            'weights_h2': self.weights_h2.copy(),\n",
    "            'bias_h2': self.bias_h2.copy(),\n",
    "            'weights_out': self.weights_out.copy(),\n",
    "            'bias_out': self.bias_out.copy(),\n",
    "            'weights_bypass_out': self.weights_bypass_out.copy(),\n",
    "            'bias_bypass_out': self.bias_bypass_out.copy(),\n",
    "            'h2_mask': self.h2_mask.copy(),\n",
    "            'use_h2': bool(self.use_h2),\n",
    "        }\n",
    "\n",
    "    def _restore(self, snap):\n",
    "        \"\"\"Restaura pesos a partir de um snapshot.\"\"\"\n",
    "        self.weights_h1 = snap['weights_h1'].copy()\n",
    "        self.bias_h1 = snap['bias_h1'].copy()\n",
    "        self.weights_h2 = snap['weights_h2'].copy()\n",
    "        self.bias_h2 = snap['bias_h2'].copy()\n",
    "        self.weights_out = snap['weights_out'].copy()\n",
    "        self.bias_out = snap['bias_out'].copy()\n",
    "        self.weights_bypass_out = snap['weights_bypass_out'].copy()\n",
    "        self.bias_bypass_out = snap['bias_bypass_out'].copy()\n",
    "        self.h2_mask = snap['h2_mask'].copy()\n",
    "        self.use_h2 = bool(snap['use_h2'])\n",
    "\n",
    "    def _train_single(self, X, y, epochs, learning_rate, use_h2_flag, h2_mask=None):\n",
    "        \"\"\"\n",
    "        Treina um único cenário e retorna o erro total ao final.\n",
    "        - use_h2_flag=True: utiliza H2 com máscara (se fornecida).\n",
    "        - use_h2_flag=False: utiliza caminho de bypass (H1->Saída).\n",
    "        \"\"\"\n",
    "        import numpy as _np\n",
    "        self.use_h2 = use_h2_flag\n",
    "        if use_h2_flag:\n",
    "            if h2_mask is None:\n",
    "                # Se não foi passada máscara, ativa todos os neurônios de H2\n",
    "                self.h2_mask = _np.ones(self.weights_h2.shape[1])\n",
    "            else:\n",
    "                self.h2_mask = _np.array(h2_mask, dtype=float)\n",
    "        total_error = 0.0\n",
    "        for epoch in range(epochs):\n",
    "            epoch_error = 0.0\n",
    "            for inputs, expected in zip(X, y):\n",
    "                final_output = self.predict(inputs, use_h2=use_h2_flag)\n",
    "                error = expected - final_output\n",
    "                epoch_error += float(np.sum(error ** 2))\n",
    "\n",
    "                d_output = error * self._sigmoid_derivative(final_output)\n",
    "\n",
    "                if use_h2_flag:\n",
    "                    # Backprop com H2 (respeitando a máscara)\n",
    "                    error_h2 = d_output.dot(self.weights_out.T)\n",
    "                    d_h2 = error_h2 * self._sigmoid_derivative(self.h2_output)\n",
    "                    # Zerar gradientes dos neurônios inativos de H2\n",
    "                    d_h2 = d_h2 * self.h2_mask\n",
    "\n",
    "                    error_h1 = d_h2.dot(self.weights_h2.T)\n",
    "                    d_h1 = error_h1 * self._sigmoid_derivative(self.h1_output)\n",
    "\n",
    "                    # Atualizações (usar h2_used para respeitar máscara no gradiente de saída)\n",
    "                    self.weights_out += self.h2_used.reshape(-1, 1) * d_output * learning_rate\n",
    "                    self.bias_out += d_output * learning_rate\n",
    "\n",
    "                    self.weights_h2 += self.h1_output.reshape(-1, 1) * d_h2 * learning_rate\n",
    "                    self.bias_h2 += d_h2 * learning_rate\n",
    "\n",
    "                    self.weights_h1 += inputs.reshape(-1, 1) * d_h1 * learning_rate\n",
    "                    self.bias_h1 += d_h1 * learning_rate\n",
    "                else:\n",
    "                    # Backprop sem H2 (via caminho de bypass)\n",
    "                    error_h1 = d_output.dot(self.weights_bypass_out.T)\n",
    "                    d_h1 = error_h1 * self._sigmoid_derivative(self.h1_output)\n",
    "\n",
    "                    # Atualizações para bypass e H1\n",
    "                    self.weights_bypass_out += self.h1_output.reshape(-1, 1) * d_output * learning_rate\n",
    "                    self.bias_bypass_out += d_output * learning_rate\n",
    "\n",
    "                    self.weights_h1 += inputs.reshape(-1, 1) * d_h1 * learning_rate\n",
    "                    self.bias_h1 += d_h1 * learning_rate\n",
    "\n",
    "            # Log de treinamento a cada 500 épocas e na última época\n",
    "            if ((epoch + 1) % 500 == 0) or ((epoch + 1) == epochs):\n",
    "                if use_h2_flag:\n",
    "                    mask_list = self.h2_mask.astype(int).tolist()\n",
    "                    false_idx = [i for i, v in enumerate(mask_list) if v == 0]\n",
    "                else:\n",
    "                    false_idx = list(range(self.weights_h2.shape[1]))\n",
    "                print(f\"Época {epoch+1}/{epochs}, use_h2={use_h2_flag}, h2_false={false_idx}, Erro: {epoch_error:.4f}\")\n",
    "\n",
    "            total_error = epoch_error\n",
    "        return total_error\n",
    "\n",
    "    def train(self, X, y, epochs=2000, learning_rate=0.1, try_both=True):\n",
    "        \"\"\"\n",
    "        Executa o treinamento.\n",
    "        - Se try_both=True: testa bypass (0 H2) e TODAS as combinações possíveis de neurônios de H2 (1..h2_size),\n",
    "          escolhe o menor erro final e mantém os pesos e a máscara referentes ao melhor cenário.\n",
    "        - Se try_both=False: treina apenas no modo atual self.use_h2 e máscara atual self.h2_mask.\n",
    "        \"\"\"\n",
    "        import time as _time\n",
    "        import itertools as _itertools\n",
    "        import numpy as _np\n",
    "        start = _time.time()\n",
    "\n",
    "        if not try_both:\n",
    "            final_error = self._train_single(X, y, epochs, learning_rate, self.use_h2, h2_mask=self.h2_mask)\n",
    "            print(f\"Treinamento concluído (use_h2={self.use_h2}, mask={self.h2_mask.astype(int).tolist()}) com erro final: {final_error:.4f}\")\n",
    "            print(f\"Tempo: {_time.time() - start:.2f}s\")\n",
    "            return {'use_h2': self.use_h2, 'final_error': final_error, 'h2_mask': self.h2_mask.copy()}\n",
    "\n",
    "        # Snapshot inicial para replicar condições em todos os cenários\n",
    "        base = self._snapshot()\n",
    "\n",
    "        results = []\n",
    "\n",
    "        # Cenário 0: bypass (use_h2=False)\n",
    "        self._restore(base)\n",
    "        err_bypass = self._train_single(X, y, epochs, learning_rate, use_h2_flag=False)\n",
    "        snap_bypass = self._snapshot()\n",
    "        results.append(('bypass', err_bypass, None, snap_bypass))\n",
    "\n",
    "        # Demais cenários: todas as combinações de 1..h2_size neurônios ativos em H2\n",
    "        h2_size = self.weights_h2.shape[1]\n",
    "        indices = list(range(h2_size))\n",
    "        for k in range(h2_size, 0, -1):\n",
    "            for combo in _itertools.combinations(indices, k):\n",
    "                mask = _np.zeros(h2_size, dtype=float)\n",
    "                mask[list(combo)] = 1.0\n",
    "                self._restore(base)\n",
    "                err = self._train_single(X, y, epochs, learning_rate, use_h2_flag=True, h2_mask=mask)\n",
    "                snap = self._snapshot()\n",
    "                results.append((f'h2_k={k}', err, mask.copy(), snap))\n",
    "\n",
    "        # Escolha do melhor cenário\n",
    "        best = min(results, key=lambda t: t[1])\n",
    "        label, chosen_err, chosen_mask, chosen_snap = best\n",
    "\n",
    "        self._restore(chosen_snap)\n",
    "        if label == 'bypass':\n",
    "            self.use_h2 = False\n",
    "            self.h2_mask = _np.zeros(h2_size)\n",
    "        else:\n",
    "            self.use_h2 = True\n",
    "            self.h2_mask = chosen_mask.copy()\n",
    "\n",
    "        print(\"Resultados SmartMLP:\")\n",
    "        print(f\"  bypass (use_h2=False) -> erro final: {err_bypass:.4f}\")\n",
    "        # Opcional: imprimir um resumo de algumas combinações testadas\n",
    "        # Aqui, mostramos apenas as melhores 3 combinações com H2 para evitar poluição de logs\n",
    "        only_h2 = [(m, e) for (lab, e, m, s) in results if lab != 'bypass']\n",
    "        only_h2_sorted = sorted(only_h2, key=lambda t: t[1])\n",
    "        for i, (m, e) in enumerate(only_h2_sorted[:3]):\n",
    "            print(f\"  h2_mask_top{i+1}={m.astype(int).tolist()} -> erro final: {e:.4f}\")\n",
    "        print(f\"  Escolhido: use_h2={self.use_h2}, mask={self.h2_mask.astype(int).tolist()} (erro {chosen_err:.4f})\")\n",
    "        print(f\"Tempo total: {_time.time() - start:.2f}s\")\n",
    "        return {\n",
    "            'use_h2': self.use_h2,\n",
    "            'final_error': chosen_err,\n",
    "            'h2_mask': self.h2_mask.copy(),\n",
    "            'err_bypass': err_bypass,\n",
    "        }\n",
]


def patch_smartmlp_cell():
    if not NB_PATH.exists():
        raise FileNotFoundError(f"Notebook não encontrado: {NB_PATH}")
    nb = json.loads(NB_PATH.read_text(encoding="utf-8"))
    cells = nb.get("cells", [])

    target_idx = None
    for i, cell in enumerate(cells):
        if cell.get("cell_type") == "code":
            src = cell.get("source", [])
            if any("class SmartMLP:" in line for line in src):
                target_idx = i
                break

    if target_idx is None:
        raise RuntimeError("Não encontrei a célula com a definição de SmartMLP no notebook.")

    # Substitui todo o conteúdo da célula por nossa implementação
    cells[target_idx]["source"] = SMARTMLP_CODE
    nb["cells"] = cells
    NB_PATH.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
    print("SmartMLP atualizado com alternância de uso da H2 e treinamento comparativo.")


if __name__ == "__main__":
    patch_smartmlp_cell()